version: "3.4"

name: hrebenikov

networks:
  nginx-php:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: test-task.nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/test-task
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: test-task.php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/test-task
    networks:
      - nginx-php
